# -*- coding: utf-8 -*-
"""analyse et graphe .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3XuOS25KOb9qIliuOUNJ6w0Ry0jJjGH
"""

# Importation des bibliothèques nécessaires
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Chargement des datasets (exemple avec URL publiques UCI)
url_red = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
url_white = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv'

# Lecture des fichiers CSV (séparateur = ';')
df_red = pd.read_csv(url_red, sep=';')
df_white = pd.read_csv(url_white, sep=';')

# Aperçu des données
print("Aperçu du vin rouge:")
print(df_red.head())
print("\nAperçu du vin blanc:")
print(df_white.head())

# Statistiques descriptives
print("\nStatistiques du vin rouge:")
print(df_red.describe())
print("\nStatistiques du vin blanc:")
print(df_white.describe())


# Préparation des données pour machine learning
# Séparation des caractéristiques (X) et de la cible (y)
X_red = df_red.drop('quality', axis=1)
y_red = df_red['quality']

X_white = df_white.drop('quality', axis=1)
y_white = df_white['quality']

# Division en ensembles d'entraînement et test (80/20)
X_red_train, X_red_test, y_red_train, y_red_test = train_test_split(X_red, y_red, test_size=0.2, random_state=42, stratify=y_red)
X_white_train, X_white_test, y_white_train, y_white_test = train_test_split(X_white, y_white, test_size=0.2, random_state=42, stratify=y_white)

# Normalisation des caractéristiques physico-chimiques
scaler = StandardScaler()
X_red_train_scaled = scaler.fit_transform(X_red_train)
X_red_test_scaled = scaler.transform(X_red_test)

X_white_train_scaled = scaler.fit_transform(X_white_train)

plt.figure(figsize=(6,5))
sns.countplot(x='quality', data=df_red, palette='Reds', hue='quality', legend=False)
plt.title('Répartition des classes de qualité - Vin Rouge')
plt.show()

plt.figure(figsize=(6,5))
sns.countplot(x='quality', data=df_white, palette='Blues', hue='quality', legend=False)
plt.title('Répartition des classes de qualité - Vin Blanc')
plt.show()