# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Minimal cleaned example (assumes a DataFrame `df` with Hours_Studied, Age, Score, Completed):
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# Create a sample DataFrame 'df' for demonstration purposes
data = {
    'Hours_Studied': np.random.rand(100) * 10,
    'Age': np.random.randint(18, 60, 100),
    'Score': np.random.rand(100) * 100,
    'Completed': np.random.choice([0, 1], 100)
}
df = pd.DataFrame(data)

# Linear regression: Score ~ Hours_Studied
X_lin = df[['Hours_Studied']].values
y_lin = df['Score'].values
lin_model = LinearRegression().fit(X_lin, y_lin)
plt.scatter(X_lin, y_lin, alpha=0.5)
xs = np.linspace(X_lin.min(), X_lin.max(), 200).reshape(-1,1)
plt.plot(xs, lin_model.predict(xs))
plt.title('Régression linéaire : Score ~ Hours_Studied')
plt.xlabel('Hours_Studied'); plt.ylabel('Score'); plt.show()

# Logistic regression: Completed ~ Hours_Studied + Age
X = df[['Hours_Studied','Age']].values
y = df['Completed'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)
logreg = LogisticRegression(max_iter=200).fit(X_train, y_train)
probs = logreg.predict_proba(X_test)[:,1]

# Plot probabilities vs Hours_Studied
hours_range = np.linspace(df['Hours_Studied'].min(), df['Hours_Studied'].max(), 300)
age_median = df['Age'].median()
X_vis = np.column_stack([hours_range, np.full_like(hours_range, age_median)])
plt.scatter(X_test[:,0], y_test, alpha=0.3, label='True labels')
plt.scatter(X_test[:,0], probs, alpha=0.6, marker='x', label='Predicted prob')
plt.plot(hours_range, logreg.predict_proba(X_vis)[:,1], linewidth=2, label=f'Logistic curve (Age={age_median})')
plt.legend(); plt.xlabel('Hours_Studied'); plt.ylabel('Probability'); plt.title('Régression logistique'); plt.show()